name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
        platform: [x86, x64]
        include:
          - platform: x64
            platform_path: x64\
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild /m /nologo /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} "Project Oceanside.sln"
    - uses: actions/upload-artifact@v1
      with:
        name: Project Oceanside-${{ matrix.configuration }}-${{ matrix.platform }}
        path: ${{ matrix.platform_path }}${{ matrix.configuration }}
